### PR TITLE
Refactor Code and Improved code readability

### LINKED ISSUE #11: Refactor Code into Separate JavaScript and CSS Files
## Description:

The current project embeds all JavaScript and CSS code within the HTML file. This proposal suggests separating these concerns into distinct files for improved maintainability and accessibility.

## Points:

Separating JavaScript and CSS into game.js and styles.css files respectively enhances code organization.
Clear separation of concerns improves code readability, aiding both current developers and potential contributors in understanding and navigating the project.

## Program contributing in:

- [x] GSSoc'24
- [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Formation-Absent/issues/new?assignees=&labels=&projects=&template=new_features_request.yml&title=%5BNew+Feature%5D%3A+) of this project.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## PR Description 📜

This PR addresses the issue of poor code readability and maintainability in the project’s HTML files. The original code had inconsistent formatting. I have separated the code from the 2 html files to their respective css and javascript files also i have improved the format of the code in styles_shrinked.css and styles_shrinked.js.

 This reorganization improves the maintainability of the codebase, making it easier for future developers to understand and extend the project. The separation of concerns ensures that HTML, CSS, and JavaScript are handled independently

 ## Changes made 

Improved formatting and indentation for better readability.
Created two new CSS files (styles1.css and styles2.css) for the two HTML files.
Organized styles with consistent formatting.
Created two new JavaScript files (script1.js and script2.js) for the two HTML files.
Improved code readability with proper formatting.
Linked each HTML file to its respective CSS and JavaScript files

Fixes #11 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
-[x] I have added screenshots for review
<hr>

image

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@roy7077 can you please review this pull request and put this with level 1 label under GSSoC'24

**Comment by roy7077** [comment]
@aditya-bhaumik  Add a screenshot of the working website

**Comment by aditya-bhaumik** [comment]
image

image

image

**Comment by aditya-bhaumik** [comment]
@roy7077 can you please put the gssoc labels for this pull request

**Comment by roy7077** [comment]
@aditya-bhaumik sure

**Pull request merged**
